"""
The 100 apps for the assignment, grouped by their assignment category.
Each entry is (name, url_hint). url_hint is a best-guess homepage to give
the agent a head start — it's optional context, not authoritative; the
agent still has to find and cite primary sources itself.
"""

APPS = [
    # 1. CRM / Sales
    ("Salesforce", "https://salesforce.com"),
    ("HubSpot", "https://hubspot.com"),
    ("Pipedrive", "https://pipedrive.com"),
    ("Attio", "https://attio.com"),
    ("Twenty", "https://twenty.com"),
    ("Podio", "https://podio.com"),
    ("Zoho CRM", "https://zoho.com/crm"),
    ("Close", "https://close.com"),
    ("Copper", "https://copper.com"),
    ("DealCloud", "https://dealcloud.com"),
    # 2. Support / Helpdesk
    ("Zendesk", "https://zendesk.com"),
    ("Intercom", "https://intercom.com"),
    ("Freshdesk", "https://freshdesk.com"),
    ("Front", "https://front.com"),
    ("Pylon", "https://usepylon.com"),
    ("LiveAgent", "https://liveagent.com"),
    ("Plain", "https://plain.com"),
    ("Help Scout", "https://helpscout.com"),
    ("Gorgias", "https://gorgias.com"),
    ("Gladly", "https://gladly.com"),
    # 3. Communications / Messaging
    ("Slack", "https://slack.com"),
    ("Twilio", "https://twilio.com"),
    ("Zoho Cliq", "https://zoho.com/cliq"),
    ("Lark", "https://larksuite.com"),
    ("Pumble", "https://pumble.com"),
    ("Discord", "https://discord.com"),
    ("Telegram", "https://telegram.org"),
    ("WhatsApp Business", "https://business.whatsapp.com"),
    ("Aircall", "https://aircall.io"),
    ("Vonage", "https://vonage.com"),
    # 4. Marketing / Ads / Email / Social
    ("Google Ads", "https://ads.google.com"),
    ("Meta Ads", "https://business.facebook.com"),
    ("LinkedIn Ads", "https://business.linkedin.com/marketing-solutions"),
    ("GoHighLevel", "https://gohighlevel.com"),
    ("Mailchimp", "https://mailchimp.com"),
    ("Klaviyo", "https://klaviyo.com"),
    ("systeme.io", "https://systeme.io"),
    ("Pinterest", "https://business.pinterest.com"),
    ("Threads", "https://threads.net"),
    ("SendGrid", "https://sendgrid.com"),
    # 5. Ecommerce
    ("Shopify", "https://shopify.com"),
    ("WooCommerce", "https://woocommerce.com"),
    ("BigCommerce", "https://bigcommerce.com"),
    ("Salesforce Commerce Cloud", "https://salesforce.com/commerce"),
    ("Magento", "https://business.adobe.com/products/magento/magento-commerce.html"),
    ("Squarespace", "https://squarespace.com"),
    ("Ecwid", "https://ecwid.com"),
    ("Gumroad", "https://gumroad.com"),
    ("Amazon SP-API", "https://developer-docs.amazon.com/sp-api"),
    ("fanbasis", "https://fanbasis.com"),
    # 6. Data / SEO / Scraping
    ("DataForSEO", "https://dataforseo.com"),
    ("SE Ranking", "https://seranking.com"),
    ("Ahrefs", "https://ahrefs.com"),
    ("MrScraper", "https://mrscraper.com"),
    ("Apify", "https://apify.com"),
    ("Firecrawl", "https://firecrawl.dev"),
    ("Bright Data", "https://brightdata.com"),
    ("Sherlock", "https://github.com/sherlock-project/sherlock"),
    ("Waterfall.io", "https://waterfall.io"),
    ("Clay", "https://clay.com"),
    # 7. Dev / Infra / Data platforms
    ("GitHub", "https://github.com"),
    ("Vercel", "https://vercel.com"),
    ("Netlify", "https://netlify.com"),
    ("Cloudflare", "https://cloudflare.com"),
    ("Supabase", "https://supabase.com"),
    ("Neo4j", "https://neo4j.com"),
    ("Snowflake", "https://snowflake.com"),
    ("MongoDB Atlas", "https://mongodb.com/atlas"),
    ("Datadog", "https://datadoghq.com"),
    ("Sentry", "https://sentry.io"),
    # 8. Productivity / PM
    ("Notion", "https://notion.so"),
    ("Airtable", "https://airtable.com"),
    ("Linear", "https://linear.app"),
    ("Jira", "https://atlassian.com/software/jira"),
    ("Asana", "https://asana.com"),
    ("Monday.com", "https://monday.com"),
    ("ClickUp", "https://clickup.com"),
    ("Coda", "https://coda.io"),
    ("Smartsheet", "https://smartsheet.com"),
    ("Harvest", "https://getharvest.com"),
    # 9. Finance
    ("Stripe", "https://stripe.com"),
    ("Plaid", "https://plaid.com"),
    ("Binance", "https://binance.com"),
    ("Paygent Connect", "https://paygent.co.jp"),
    ("iPayX", "https://ipayx.io"),
    ("QuickBooks", "https://quickbooks.intuit.com"),
    ("Xero", "https://xero.com"),
    ("Brex", "https://brex.com"),
    ("Ramp", "https://ramp.com"),
    ("PitchBook", "https://pitchbook.com"),
    # 10. AI / Research / Media
    ("NotebookLM", "https://notebooklm.google"),
    ("Otter AI", "https://otter.ai"),
    ("Fathom", "https://fathom.video"),
    ("Consensus", "https://consensus.app"),
    ("Reducto", "https://reducto.ai"),
    ("Devin", "https://devin.ai"),
    ("higgsfield", "https://higgsfield.ai"),
    ("Mermaid CLI", "https://github.com/mermaid-js/mermaid-cli"),
    ("YouTube Transcript", "https://developers.google.com/youtube/v3"),
    ("Grain", "https://grain.com"),
]

assert len(APPS) == 100, f"expected 100 apps, got {len(APPS)}"
